# Generated by Django 5.0.2 on 2024-03-02 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa_serial_numbers',
            name='last_checked',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
