# Generated by Django 5.0.2 on 2024-03-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_sa_serial_numbers_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sa_serial_numbers',
            name='last_checked',
        ),
    ]
