# Generated by Django 5.0.2 on 2024-03-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_sa_serial_numbers_last_checked'),
    ]

    operations = [
    ]
