# Generated by Django 5.0.2 on 2024-03-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20240302_0350'),
    ]

    operations = [
    ]
