# Generated by Django 5.0.2 on 2024-03-02 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20240302_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa_serial_numbers',
            name='last_checked',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
