# Generated by Django 5.0.2 on 2024-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_teacherpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherpack_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('last_checked', models.CharField(max_length=100)),
                ('sa_serial_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacherpack_table',
                'managed': False,
            },
        ),
    ]
