# Generated by Django 5.0.2 on 2024-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_teacherpack_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacherpack',
        ),
        migrations.DeleteModel(
            name='teacherpack_table',
        ),
    ]
