# Generated by Django 5.0.2 on 2024-03-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_raspberry_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='raspberry_pi_table',
            fields=[
                ('last_checked', models.CharField(max_length=100)),
                ('sa_serial_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raspberry_pi_table',
                'managed': False,
            },
        ),
    ]
